networks:
  storage:
    name: "storage"
    external: true
  overmoney:

services:
  api:
    image: localhost:5000/overmoney_api
    container_name: overmoney_api
    restart: unless-stopped
    ports:
      - 9100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=storage-postgresql-1:5432;Database=overmoney;Username=hyperion;Password=hyperion
      - ASPNETCORE_URLS=http://+:80
      - AutoMigrate=true
    networks:
      - storage
      - overmoney

  portal:
    image: localhost:5000/overmoney_portal
    container_name: overmoney_portal
    restart: unless-stopped
    ports:
      - 9101:80
      - 9102:9102
    networks:
      - overmoney
    volumes:
        - /var/lib/docker-config/overmoney/nginx/default.conf:/etc/nginx/conf.d/default.conf
    