name: build
on: push

env:
    PROJECT_NAME: src/
    DOCKER_FILE: src/Overmoney.Api/Dockerfile

jobs:
    build-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            
            - name: Dotnet restore
              run: dotnet restore ${{ env.PROJECT_NAME }}

            - name: Dotnet build
              run: dotnet build --no-restore ${{ env.PROJECT_NAME }}

            - name: Run tests
              run: dotnet test --no-restore ${{ env.PROJECT_NAME }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and export Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ${{ env.DOCKER_FILE }}
                tags: overmoney_api
                outputs: type=docker,dest=/tmp/overmoney_api.tar

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: overmoney_api
                path: /tmp/overmoney_api.tar